### ISSUE TITLE
http://localhost:3000/swagger-html 404 not found?

### ISSUE THREAD

**Issue by xieyezi** [Cody2333/koa-swagger-decorator#72]
跟着文档配置了一遍，但是当我运行之后，访问 "http://localhost:3000/swagger-html"  ，没有api文档生成？ 这是我的`router.ts` ： [router.ts](https://github.com/xieyezi/KoaWithTypeScript/blob/master/src/routes/router.ts)

**Comment by Cody2333** [comment]
可以的话，麻烦提供一个可运行的示例代码的仓库，我测试一下

**Comment by xieyezi** [comment]
你好，谢谢回复。是我自己的配置问题，我将`router.mapDir(__dirname + '/../');`设置为我的路由映射就可以了。谢谢！

**Comment by kevinblade** [comment]
Hello. I couldn't view http://localhost:3000/api/swagger-html that reason is  as following error **"Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self'". Either the 'unsafe-inline' keyword, a hash ('sha256-aprqhcGIuEdFHjJ3tLbisxpYmlmPTnIKzn9fwWb7iGg='), or a nonce ('nonce-...') is required to enable inline execution."**

What is the problem?
